In [1]:
#1
import os
import hashlib

def find_duplicate_files(path):
    # dictionary to store file paths and their corresponding hashes
    hashes = {}
    duplicates = []
# walk through all the directories and subdirectories
    for root, dirs, files in os.walk(path):
        for file in files:
            # get the full path of the file
            file_path = os.path.join(root, file)

            # calculate the hash of the file contents
            with open(file_path, 'rb') as f:
                file_hash = hashlib.md5(f.read()).hexdigest()

            # if the hash already exists in the dictionary, add it to the list of duplicates
            if file_hash in hashes:
                duplicates.append((file_path, hashes[file_hash]))
            else:
                hashes[file_hash] = file_path

    return duplicates

def delete_duplicates(duplicates):
    for duplicate in duplicates:
        # print the duplicates before deleting
        print(f'Deleting {duplicate[0]} (duplicate of {duplicate[1]})')

        # delete the duplicate file
        os.remove(duplicate[0])

if __name__ == '__main__':
    path = input('Enter the path to search for duplicates: ')
    duplicates = find_duplicate_files(path)

    if duplicates:
        print(f'{len(duplicates)} duplicate files found:')
        for duplicate in duplicates:
            print(f'{duplicate[0]} (duplicate of {duplicate[1]})')

        delete = input('Do you want to delete the duplicates? (y/n): ')
        if delete.lower() == 'y':
            delete_duplicates(duplicates)
            print('Duplicates deleted successfully!')
        else:
            print('Duplicates not deleted.')
    else:
        print('No duplicate files found.')





Enter the path to search for duplicates: D:\files
1 duplicate files found:
D:\files\hello1.txt (duplicate of D:\files\hello.txt)
Do you want to delete the duplicates? (y/n): y
Deleting D:\files\hello1.txt (duplicate of D:\files\hello.txt)
Duplicates deleted successfully!


In [3]:
#3 and 4
import math

# create a 2D array of size 5x5 with random integers
arr = [[7, 3, 8, 2, 6],
       [5, 1, 9, 4, 10],
       [13, 17, 12, 11, 15],
       [14, 16, 19, 20, 18],
       [22, 21, 23, 25, 24]]

# loop through the array and update prime number positions with their cube
for i in range(len(arr)):
    for j in range(len(arr[i])):
        if math.isqrt(arr[i][j]) ** 2 == arr[i][j]:  # check if number is not prime
            continue
        else:  # number is prime
            arr[i][j] = arr[i][j] ** 3

# calculate the sum of every cubed value and its previous integer
total_sum = 0
for i in range(len(arr)):
    for j in range(len(arr[i])):
        if j > 0:
            total_sum += arr[i][j] + arr[i][j-1]
        if i > 0:
            total_sum += arr[i][j] + arr[i-1][j]

print(arr)
print("Total sum:", total_sum)




[[343, 27, 512, 8, 216], [125, 1, 9, 4, 1000], [2197, 4913, 1728, 1331, 3375], [2744, 16, 6859, 8000, 5832], [10648, 9261, 12167, 25, 13824]]
Total sum: 253325


In [2]:
#2
import random
import string
def random_password(length):
    upperletters=string.ascii_uppercase
    lowerletters=string.ascii_lowercase
    digits=string.digits
    result1=''.join(random.choice(upperletters)for i in range(1))
    result2=''.join(random.choice(lowerletters)for i in range(2))
    result3=''.join(random.choice(digits)for i in range(3))
    resultpassword=result1+result2+result3
    resultpassword=''.join(random.sample(resultpassword,len(resultpassword)))
    print("random password= ",resultpassword)
    
print(random_password(6))

random password=  8t5lA2
None


In [18]:
#7
arr2=np.ones((7,7),dtype='int8')
arr2[1::2,::2]=0
arr2[::2,1::2]=0
arr2

array([[1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1]], dtype=int8)

In [41]:
#6
arr3=np.arange(7,(7*49)+1,7).reshape(7,7)
print(arr3)

print(arr3[6][6])

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]
343


###### 

In [48]:
#5
arr1=np.array([1,3,4,5,7])
arr2=np.array([2,3,5,6])

arr3 = np.intersect1d(arr1,arr2)
print(arr3)

[3 5]


In [5]:
#8
# create the matrix as a list of lists
l1 = [['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H'],
       ['I', 'a', 'K', 'L'],
       ['M', 'N', 'o', 'P'],
       ['Q', 'R', 'S', 'T'],
       ['U', '0', 'W', 'O']]

# define vowels to replace with None
vowels = ['A', 'E', 'I', 'O', 'U', 'a', 'o']

# replace vowels with None
for i in range(len(l1)):
    for j in range(len(l1[i])):
        if l1[i][j] in vowels:
            l1[i][j] = None

# count missing values
count_none = sum(1 for row in l1 for val in row if val is None)

print(l1)
print("Number of missing values:", count_none)







[[None, 'B', 'C', 'D'], [None, 'F', 'G', 'H'], [None, None, 'K', 'L'], ['M', 'N', None, 'P'], ['Q', 'R', 'S', 'T'], [None, '0', 'W', None]]
Number of missing values: 7
